### PR TITLE
Adds support for synonyms

### PR DESCRIPTION
**Pull request by GiampaoloFalqui**

### CODE REVIEW

**Comment by GiampaoloFalqui** [comment]
Sorry for the mess. Had to hard-reset the branch otherwise there were like 15 useless commits in attempt to rebase the branch. @maxiloc

**Comment by maxiloc** [comment]
No problem, looks good. Could you add a test ? After that we can merge

**Comment by GiampaoloFalqui** [comment]
Done!

**Comment by maxiloc** [comment]
@GiampaoloFalqui Thanks for contributing

**Pull request merged**
